version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/todoproject:latest .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push  $DOCKERHUB_USERNAME/todoproject:latest
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i /path/to/your/key ec2-user@3.110.183.35 << EOF
              docker pull $DOCKERHUB_USERNAME/todoproject:latest
              # Implement your deployment strategy here (e.g., stop old container, start new container)
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy