version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the application
          command: npm run build
      - run:
          name: Build Docker image
          command: docker build -t todo-app .
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image
          command: docker tag todo-app $DOCKERHUB_USERNAME/todo-app:$CIRCLE_SHA1 && docker push $DOCKERHUB_USERNAME/todo-app:$CIRCLE_SHA1
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i /path/to/react-web.pem ubuntu@your-ec2-public-dns 'bash -s' < deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
