version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the application
          command: npm run build
      - run:
          name: Build Docker image
          command: docker build -t todo-app .
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image
          command: docker tag todo-app $DOCKERHUB_USERNAME/todo-app:$CIRCLE_SHA1 && docker push $DOCKERHUB_USERNAME/todo-app:$CIRCLE_SHA1
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"  # Replace with the fingerprint of your SSH key
      - run:
          name: Deploy to EC2
          command: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy.sh ubuntu@ec2-3-110-183-35.ap-south-1.compute.amazonaws.com:~/
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-3-110-183-35.ap-south-1.compute.amazonaws.com 'bash ~/deploy.sh'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
